final build+humour.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -56,42 +56,13 @@ jobs:
         continue-on-error: true
 
      
-      - name: Rickroll on test failure
+      - name: Test failed diagnostic
         if: steps.build-and-test.outcome == 'failure'
         run: |
-          echo " "
-          echo "::warning::A GraphHopper test failed. Initializing RICKROLL sequence..."
-          echo " "
-          cat << 'EOF'
-⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀ ⢀⣤⡤⠤⠤⠤⢤⣤⣤⣀⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
-⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢶⡏⠁⠀⠀⠀⠀⠀⠀⠀⠈⠉⠓⢦⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
-⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣴⠿⠞⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠘⢷⣆⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
-⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣼⣿⠀⠀⠀⠀⠀⣀⣀⣀⠀⠀⠀⠀⡀⠀⠀⠀⠈⢿⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
-⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢹⣿⠀⢀⣴⠟⠉⠁⠀⠈⠉⠉⠋⠉⠉⠙⢷⡀⠀⢸⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
-⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⡇⠀⣸⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣷⠀⢸⡅⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
-⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿⡁⢀⡟⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⠀⢸⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
-⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣸⣷⡿⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⢤⣼⠆⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
-⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠸⣿⠉⠉⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⣿⠟⠃⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
-⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠹⡄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⠛⣾⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
-⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠻⠶⣦⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢠⣾⠃⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
-⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣴⡿⠃⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
-⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿⡆⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣸⠏⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
-⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣿⠃⠀⠀⠀⠀⠀⠀⠀⠀⠀⠠⣿⣄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
-⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣀⣾⣿⣀⣀⣀⣀⠀⠀⠀⠀⠀⠀⢀⣿⡌⠳⣄⣀⣀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
-⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣠⡴⠾⡟⢿⠏⠉⠉⠉⢻⡇⠀⠀⠀⠀⠀⣼⢻⣇⠀⠀⠈⠉⠛⠳⠶⠤⣤⣄⡀⠀⠀⠀⠀⠀⠀⠀⠀
-⠀⠀⠀⠀⠀⠀⢀⣠⡴⠞⠋⠁⠀⣰⡇⢸⠀⠀⠀⢀⢸⡇⠀⠀⠀⣠⡾⠃⢸⣿⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⠙⠛⠲⠤⢤⣄⡀⠀⠀
-⠀⠀⠀⣀⣤⠖⠋⠁⠀⠀⠀⠀⠀⣿⠀⢸⠀⠀⠀⢸⣾⠇⠀⢀⣼⠛⠁⠀⣸⠫⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠉⠳⣄⠀
-⠀⣴⠊⠉⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿⠀⢸⠀⠀⠀⠀⢿⣦⠾⠋⠁⠀⠀⣴⠏⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠙⡦
-⢰⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠠⣿⣀⣼⣧⣤⣶⣤⣽⠿⣦⡀⠀⢠⡜⣿⠂⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿
-⢸⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⢻⡇⢠⣿⠿⣇⠀⠀⠀⠉⠛⠁⢠⡟⠀⠀⠀⠀⠀⠀⠀⠀⣠⣶⣤⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿
-⢸⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿⢸⡇⠀⡏⠀⠀⠀⠀⠀⠀⢼⡇⠀⠀⠀⠀⠀⠀⠀⠰⣿⡂⠸⡄⠀⠀⠀⠀⠀⠀⠀⢀⣿
-⢸⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿⢸⠇⠀⣿⠀⠀⠀⠀⠀⠀⢻⠇⠀⠀⠀⠀⠀⠀⠀⠀⠸⡇⠀⣿⡀⢀⡰⠾⣷⣀⠀⣿⠃
-⠀⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢿⣿⡀⢀⣿⠀⠀⠀⠀⠀⠀⢸⡆⠀⠀⠀⠀⠀⠀⠀⠀⠀⡇⠀⠘⢷⣏⣠⠼⣷⣿⣆⣸⣟
-⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⣞⣷⣿⡁⠀⠀⠀⠀⠀⠀⢸⡧⠀⠀⠀⠀⠀⠀⠀⠀⠠⡇⠀⠀⢠⢯⡁⢸⣯⡀⢸⣏⣉
-EOF
-          echo " "
-          echo "::error::You have been rickrolled. https://www.youtube.com/watch?v=dQw4w9WgXcQ"
-          exit 1
+          echo "Tests failed! Commit: https://www.youtube.com/watch?v=dQw4w9WgXcQ by Rick"
+          echo "Take a deep breath..."
+          echo "Never gonna give you up!"
+          exit 1    
 
       - name: Run mutation analysis and update baseline
         if: |
@@ -134,7 +105,7 @@ EOF
 
           # Update baseline if improved
           if [ "$CUR_SCORE" -gt "$PREV_SCORE" ]; then
-            echo "🎉 Mutation score improved! Updating baseline..."
+            echo " Mutation score improved! Updating baseline..."
 
             git config --global user.name 'github-actions[bot]'
             git config --global user.email 'github-actions[bot]@users.noreply.github.com'
